__author__ = 'yueeong'

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''


def fiboevensummer():
    fibolist = [1,2,3]  #initial start
    evensum = 2

    maxval = 0
    count = 2  #start to append
    while maxval < 4000000:
        maxval = fibolist[count] + fibolist[count-1]
        fibolist.append(maxval)
        print maxval
        if maxval % 2 == 0 & maxval < 4000000:
            evensum += maxval
        count += 1

    print evensum







fiboevensummer()